spring.application.name=orchestrator-service
server.port=8083

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

orchestrator.gesture.confidence-threshold=0.6

logging.level.com.example.orchestratorservice=DEBUG
